basePath: /
host: localhost:8000
info:
  contact: {}
  description: Api server for TodoList Application
  title: TODO APP API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
